export const GET_PROJECTS_START = 'GET_PROJECTS_START';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const SELECT_PROJECT = 'SELECT_PROJECT';
export const SELECT_BRANCH = 'SELECT_BRANCH';
