export const GET_CIRCLECI_BUILDS_START = 'GET_CIRCLECI_BUILDS_START'
export const GET_CIRCLECI_BUILDS_SUCCESS = 'GET_CIRCLECI_BUILDS_SUCCESS'
export const GET_CIRCLECI_BUILDS_ERROR = 'GET_CIRCLECI_BUILDS_ERROR'
export const SELECT_CIRCLECI_BUILD = 'SELECT_CIRCLECI_BUILD'
