export const GET_BUILDS_START = 'GET_BUILDS_START';
export const GET_BUILDS_SUCCESS = 'GET_BUILDS_SUCCESS';
export const GET_BUILDS_ERROR = 'GET_BUILDS_ERROR';
export const GET_BUILD_START = 'GET_BUILD_START';
export const GET_BUILD_SUCCESS = 'GET_BUILD_SUCCESS';
export const GET_BUILD_ERROR = 'GET_BUILD_ERROR';
export const SELECT_BUILD = 'SELECT_BUILD';